project_id = "nmsblmmhigwsevnqmhwn"

[functions.send-whatsapp]
verify_jwt = false

[functions.send-whatsapp-evolution]
verify_jwt = false

[functions.expire-waitlist]
verify_jwt = false

[functions.notify-waitlist]
verify_jwt = false
