project_id = "nmsblmmhigwsevnqmhwn"

[functions.send-whatsapp]
verify_jwt = false

[functions.send-whatsapp-evolution]
verify_jwt = false

[functions.expire-waitlist]
verify_jwt = false

[functions.notify-waitlist]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.send-monthly-earnings-report]
verify_jwt = false

[functions.whatsapp-chatbot]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false
